CREATE TABLE BIRDIE_BOGEY_RATIO_CLEANED AS (
	SELECT
		*
	FROM
		(
			SELECT
				PLAYER,
				TOURNAMENT_DATE,
				TOURNAMENT_NAME,
				CASE
					WHEN "TOTAL BIRDIES AND BETTER" < DIFF_BIRDIES THEN "TOTAL BIRDIES AND BETTER"
					ELSE "TOTAL BIRDIES AND BETTER" - COALESCE(DIFF_BIRDIES, 0)
				END AS BIRDIES_AND_BETTER,
				CASE
					WHEN "TOTAL BOGEYS AND WORSE" < DIFF_BOGEYS THEN "TOTAL BOGEYS AND WORSE"
					ELSE "TOTAL BOGEYS AND WORSE" - COALESCE(DIFF_BOGEYS, 0)
				END AS BOGEYS_AND_WORSE
			FROM
				(
					SELECT
						PLAYER,
						TOURNAMENT_DATE,
						TOURNAMENT_NAME,
						"TOTAL BIRDIES AND BETTER",
						LAG("TOTAL BIRDIES AND BETTER") OVER (
							PARTITION BY
								PLAYER
							ORDER BY
								TOURNAMENT_DATE ASC,
								"TOTAL BIRDIES AND BETTER" ASC
						) AS DIFF_BIRDIES,
						"TOTAL BOGEYS AND WORSE",
						LAG("TOTAL BOGEYS AND WORSE") OVER (
							PARTITION BY
								PLAYER
							ORDER BY
								TOURNAMENT_DATE ASC,
								"TOTAL BOGEYS AND WORSE" ASC
						) AS DIFF_BOGEYS
					FROM
						BIRDIE_BOGEY_RATIO
				)
		)
)