CREATE TABLE BIRDIES_CLEANED AS (
	SELECT
		*
	FROM
		(
			SELECT
				PLAYER,
				TOURNAMENT_DATE,
				TOURNAMENT_NAME,
				CASE
					WHEN TOTAL < DIFF_BIRDIES THEN TOTAL
					ELSE TOTAL - COALESCE(DIFF_BIRDIES, 0)
				END AS BIRDIES
			FROM
				(
					SELECT
						PLAYER,
						TOURNAMENT_DATE,
						TOURNAMENT_NAME,
						TOTAL,
						LAG(TOTAL) OVER (
							PARTITION BY
								PLAYER
							ORDER BY
								TOURNAMENT_DATE ASC
						) AS DIFF_BIRDIES
					FROM
						BIRDIES
				)
		)
)