SELECT
	*, DISTANCE / DRIVES AS AVG_DISTANCE
FROM
	(
		SELECT
			PLAYER,
			TOURNAMENT_DATE,
			TOURNAMENT_NAME,
			CASE
				WHEN "TOTAL DRIVES" < DIFF_DRIVES THEN "TOTAL DISTANCE"
				ELSE "TOTAL DISTANCE" - COALESCE(DIFF_DISTANCE, 0)
			END AS DISTANCE,
			CASE
				WHEN "TOTAL DRIVES" < DIFF_DRIVES THEN "TOTAL DRIVES"
				ELSE "TOTAL DRIVES" - COALESCE(DIFF_DRIVES, 0)
			END AS DRIVES
		FROM
			(
				SELECT
					PLAYER,
					TOURNAMENT_DATE,
					TOURNAMENT_NAME,
					"TOTAL DISTANCE",
					LAG("TOTAL DISTANCE") OVER (
						PARTITION BY
							PLAYER
						ORDER BY
							TOURNAMENT_DATE ASC,
							"TOTAL DRIVES" ASC
					) AS DIFF_DISTANCE,
					"TOTAL DRIVES",
					LAG("TOTAL DRIVES") OVER (
						PARTITION BY
							PLAYER
						ORDER BY
							TOURNAMENT_DATE ASC,
							"TOTAL DRIVES" ASC
					) AS DIFF_DRIVES
				FROM
					(
						SELECT
							PLAYER,
							TOURNAMENT_DATE,
							TOURNAMENT_NAME,
							CAST(CAST("TOTAL DISTANCE" AS MONEY) AS NUMERIC) AS "TOTAL DISTANCE",
							"TOTAL DRIVES"
						FROM
							DRIVING_DISTANCE
					)
			)
	)
WHERE DRIVES > 0