-- Strokes Gained Total
CREATE TABLE SG_TOTAL (
    RANK FLOAT,
    PLAYER VARCHAR(255),
    AVG FLOAT,
    "TOTAL SG:T" FLOAT,
    "TOTAL SG:T2G" FLOAT,
    "TOTAL SG:P" FLOAT,
    "MEASURED ROUNDS" FLOAT,
    TOURNAMENT_DATE DATE,
    TOURNAMENT_NAME VARCHAR(255),
    PRIMARY KEY (RANK, PLAYER, TOURNAMENT_DATE, TOURNAMENT_NAME)
);

-- Strokes Gained T2G
CREATE TABLE SG_T2G (
    RANK FLOAT,
    PLAYER VARCHAR(255),
    AVG FLOAT,
    "SG:OTT" FLOAT,
    "SG:APR" FLOAT,
    "SG:ARG" FLOAT,
    "MEASURED ROUNDS" FLOAT,
    TOURNAMENT_DATE DATE,
    TOURNAMENT_NAME VARCHAR(255),
    PRIMARY KEY (RANK, PLAYER, TOURNAMENT_DATE, TOURNAMENT_NAME)
);

-- Birdie Bogey Ratio (Pars, Eagles, Double Bogeys)
CREATE TABLE BIRDIE_BOGEY_RATIO (
    RANK FLOAT,
    PLAYER VARCHAR(255),
    "BIRDIE TO BOGEY RATIO" FLOAT,
    "TOTAL BIRDIES AND BETTER" FLOAT,
    "TOTAL BOGEYS AND WORSE" FLOAT,
    TOURNAMENT_DATE DATE,
    TOURNAMENT_NAME VARCHAR(255),
    PRIMARY KEY (RANK, PLAYER, TOURNAMENT_DATE, TOURNAMENT_NAME)
);

-- Birdies
CREATE TABLE BIRDIES (
    RANK FLOAT,
    PLAYER VARCHAR(255),
    TOTAL FLOAT,
    TOURNAMENT_DATE DATE,
    TOURNAMENT_NAME VARCHAR(255),
    PRIMARY KEY (RANK, PLAYER, TOURNAMENT_DATE, TOURNAMENT_NAME)
);

-- Bogeys
CREATE TABLE BOGEYS (
    RANK FLOAT,
    PLAYER VARCHAR(255),
    "AVERAGE BOGEYS PER ROUND" FLOAT,
    "TOTAL BOGEYS" FLOAT,
    "ROUNDS PLAYED" FLOAT,
    TOURNAMENT_DATE DATE,
    TOURNAMENT_NAME VARCHAR(255),
    PRIMARY KEY (RANK, PLAYER, TOURNAMENT_DATE, TOURNAMENT_NAME)
);

-- Tournament Results
CREATE TABLE TOURNAMENT_RESULTS (
    RANK FLOAT,
    PLAYER VARCHAR(255),
    MONEY MONEY,
    TOURNAMENT_DATE DATE,
    TOURNAMENT_NAME VARCHAR(255),
    PRIMARY KEY (RANK, PLAYER, TOURNAMENT_DATE, TOURNAMENT_NAME)
);

-- Driving Distance
CREATE TABLE DRIVING_DISTANCE (
    RANK FLOAT,
    PLAYER VARCHAR(255),
    AVG FLOAT,
    "TOTAL DISTANCE" VARCHAR(255),
    "TOTAL DRIVES" FLOAT,
    TOURNAMENT_DATE DATE,
    TOURNAMENT_NAME VARCHAR(255),
    PRIMARY KEY (RANK, PLAYER, TOURNAMENT_DATE, TOURNAMENT_NAME)
);

-- Driving Accuracy
CREATE TABLE DRIVING_ACCURACY (
    RANK FLOAT,
    PLAYER VARCHAR(255),
    "%" FLOAT,
    "FAIRWAYS HIT" VARCHAR(255),
    "POSSIBLE FAIRWAYS" VARCHAR(255),
    TOURNAMENT_DATE DATE,
    TOURNAMENT_NAME VARCHAR(255),
    PRIMARY KEY (RANK, PLAYER, TOURNAMENT_DATE, TOURNAMENT_NAME)
);