-- Strokes Gained Total
CREATE TABLE SG_TOTAL (
    RANK FLOAT,
    PLAYER VARCHAR(255),
    AVG FLOAT,
    "TOTAL SG:T" FLOAT,
    "TOTAL SG:T2G" FLOAT,
    "TOTAL SG:P" FLOAT,
    "MEASURED ROUNDS" FLOAT,
    TOURNAMENT_DATE DATE,
    TOURNAMENT_NAME VARCHAR(255),
    PRIMARY KEY (RANK, PLAYER, TOURNAMENT_DATE, TOURNAMENT_NAME)
);

-- Strokes Gained T2G
CREATE TABLE SG_T2G (
    RANK FLOAT,
    PLAYER VARCHAR(255),
    "SG:OTT" FLOAT,
    "SG:APR" FLOAT,
    "SG:ARG" FLOAT,
    "MEASURED ROUNDS" INTEGER,
    TOURNAMENT_DATE DATE,
    TOURNAMENT_NAME VARCHAR(255),
    PRIMARY KEY (PLAYER_ID)
);

-- Birdie Bogey Ratio (Pars, Eagles, Double Bogeys)
CREATE TABLE BIRDIE_BOGEY_RATIO (
    PLAYER_ID SERIAL,
    PLAYER VARCHAR(255),
    "TOTAL BIRDIES AND BETTER" INTEGER,
    "TOTAL BOGEYS AND WORSE" INTEGER,
    TOURNAMENT_DATE DATE,
    TOURNAMENT_NAME VARCHAR(255),
    PRIMARY KEY (PLAYER_ID)
);

-- Birdies
CREATE TABLE BIRDIES (
    PLAYER_ID SERIAL,
    PLAYER VARCHAR(255),
    TOTAL INTEGER,
    TOURNAMENT_DATE DATE,
    TOURNAMENT_NAME VARCHAR(255),
    PRIMARY KEY (PLAYER_ID)
);

-- Bogeys
CREATE TABLE BOGEYS (
    PLAYER_ID SERIAL,
    PLAYER VARCHAR(255),
    "TOTAL BOGEYS" INTEGER,
    "ROUNDS PLAYED" INTEGER,
    TOURNAMENT_DATE DATE,
    TOURNAMENT_NAME VARCHAR(255),
    PRIMARY KEY (PLAYER_ID)
);

CREATE TABLE TOURNAMENT_RESULTS (
    PLAYER_ID SERIAL,
    PLAYER VARCHAR(255),
    MONEY INTEGER,
    TOURNAMENT_DATE DATE,
    TOURNAMENT_NAME VARCHAR(255),
    PRIMARY KEY (PLAYER_ID)
);

CREATE TABLE DRIVING_DISTANCE (
    PLAYER_ID SERIAL,
    PLAYER VARCHAR(255),
    "TOTAL DISTANCE" INTEGER,
    "TOTAL DRIVES" INTEGER,
    TOURNAMENT_DATE DATE,
    TOURNAMENT_NAME VARCHAR(255),
    PRIMARY KEY (PLAYER_ID)
);

CREATE TABLE DRIVING_ACCURACY (
    PLAYER_ID SERIAL,
    PLAYER VARCHAR(255),
    "FAIRWAYS HIT" INTEGER,
    "POSSIBLE FAIRWAYS" INTEGER,
    TOURNAMENT_DATE DATE,
    TOURNAMENT_NAME VARCHAR(255),
    PRIMARY KEY (PLAYER_ID)
);