SELECT
	*
FROM
	(
		SELECT
			PLAYER,
			TOURNAMENT_DATE,
			TOURNAMENT_NAME,
			CASE
				WHEN "MEASURED ROUNDS" < DIFF_ROUNDS THEN "SG:OTT"
				ELSE "SG:OTT" - COALESCE(DIFF_SG_OTT, 0)
			END AS SG_OTT,
			CASE
				WHEN "MEASURED ROUNDS" < DIFF_ROUNDS THEN "SG:APR"
				ELSE "SG:APR" - COALESCE(DIFF_SG_APR, 0)
			END AS SG_APR,
			CASE
				WHEN "MEASURED ROUNDS" < DIFF_ROUNDS THEN "SG:ARG"
				ELSE "SG:ARG" - COALESCE(DIFF_SG_ARG, 0)
			END AS SG_ARG,
			CASE
				WHEN "MEASURED ROUNDS" < DIFF_ROUNDS THEN "MEASURED ROUNDS"
				ELSE "MEASURED ROUNDS" - COALESCE(DIFF_ROUNDS, 0)
			END AS ROUNDS
		FROM
			(
				SELECT
					PLAYER,
					TOURNAMENT_DATE,
					TOURNAMENT_NAME,
					"SG:OTT",
					LAG("SG:OTT") OVER (
						PARTITION BY
							PLAYER
						ORDER BY
							TOURNAMENT_DATE ASC,
							"MEASURED ROUNDS" ASC
					) AS DIFF_SG_OTT,
					"SG:APR",
					LAG("SG:APR") OVER (
						PARTITION BY
							PLAYER
						ORDER BY
							TOURNAMENT_DATE ASC,
							"MEASURED ROUNDS" ASC
					) AS DIFF_SG_APR,
					"SG:ARG",
					LAG("SG:ARG") OVER (
						PARTITION BY
							PLAYER
						ORDER BY
							TOURNAMENT_DATE ASC,
							"MEASURED ROUNDS" ASC
					) AS DIFF_SG_ARG,
					"MEASURED ROUNDS",
					LAG("MEASURED ROUNDS") OVER (
						PARTITION BY
							PLAYER
						ORDER BY
							TOURNAMENT_DATE ASC,
							"MEASURED ROUNDS" ASC
					) AS DIFF_ROUNDS
				FROM
					(
						SELECT
							PLAYER,
							TOURNAMENT_DATE,
							TOURNAMENT_NAME,
							"SG:OTT" * "MEASURED ROUNDS" AS "SG:OTT",
							"SG:APR" * "MEASURED ROUNDS" AS "SG:APR",
							"SG:ARG" * "MEASURED ROUNDS" AS "SG:ARG",
							"MEASURED ROUNDS"
						FROM
							SG_T2G
					)
			)
	)
WHERE
	ROUNDS > 0
	AND ROUNDS <= 4